# عادت اندازه گیری شهودی

افرادی که به ما یاد دادند که حس شهودی به بررسی‌های کمّی چگونه باید باشد:

- در یونان باستان، 
مردی با نگاه به طول سایه‌ها در شهرهای مختلف در رأس ۱۲ ظهر و
به کار گیری چند روش هندسی ساده، محیط کره‌ی زمین را برآورد کرد.

- فیزیکدان برنده‌ی جایزه نوبل به دانشجویانش یاد داد که چگونه می‌توانند
مقادیری مانند تعداد تعمیرکاران پیانو در شیکاگو را، که هیچ داده‌ی اولیه‌ای
درباره‌شان ندارند، برآورد کنند.

- دختری نه ساله‌ای آزمایشی را ترتیب داد که بر روش
«لمس درمانی»
که هر روز بر طرف دارانش افزوده می‌شد، خط بطلان کشید، و دو سال بعد،
جوان ترین فردی شد که تاکنون در نشریه‌ی
انجمن پزشکی آمریکا مقاله چاپ کرده است.

## برآورد کردن: مانند انریکو فرمی باشید {-}

:::::: {.example} ::::::

روش اندازه گیری تعداد تعمیر کاران در شیکاگو:

\[\scriptsize
\begin{aligned}
\text{Tuners in Chicago} & =
  \cfrac{\text{Population}}{\text{People per Household}} \\
  & \times \text{Percentage of Households with Tuned Pianos} \\
  & \times \cfrac{
    \text{Tunings per Year per Piano}
    }{
    {\text{Tunings per Tuner per Day}
      \times \text{Workdays per Year}
  }}
\end{aligned}
\]

::: {.ltr} ::: 
[Tuners in Chicago]{dir=ltr} =
تعداد تعمیرکاران در شیکاگو

[Population]{dir=ltr} =
جمعیت

[People per Household]{dir=ltr} =
تعداد افراد هر خانوار

[Percentage of Households with Tuned Pianos]{dir=ltr} =
درصد خانوارهای دارای پیانوی تعمیر شده

[Tunings per Year per Piano]{dir=ltr} =
تعداد تعمیر هر پیانو در هر سال

[Tunings per Tuner per Day]{dir=ltr} =
تعداد تعمیر در هر روز

[Workdays per Year]{dir=ltr} =
روزهای کاری در هر سال
:::::

:::::::::::

::: {.remark} :::
اندازه گیری به معنای 
«کاهش عدم قطعیت»
و نه لزوما به صفر رساندن آن است.
::::::